coaching_task:
  description: >
    Provide insightful guidance on {topic}, tailoring your response based on the selected skills: {skills}.
    Use {skills} as needed to engage effectively with the user.
  expected_output: >
    A list of 5 key insights about {topic}, presented in a style influenced by the selected {skills}.
  agent: coach

writing_task:
  description: >
    Expand on the insights provided by the coach, crafting a full report based on {topic}.
    The report should be adapted according to the selected skills: {skills}, ensuring it resonates with the intended audience.
  expected_output: >
    A complete markdown report with sections for each main topic, written in a style aligned with the chosen skills.
  agent: writer
